export const merchantLexicon = [
  'African Shop (any)',
  'Aldi',
  'ALDI STORES',
  'Albertsons',
  'Amazon Fresh',
  'Auchan',
  'Asda',
  'Biedronka',
  'Big Bazaar',
  'Big Lots',
  'Billa',
  'BJs Wholesale Club',
  'Boots',
  'Carrefour',
  'Carrefour Express',
  'Casino',
  'City Market',
  'Coles',
  'Co-op',
  'Consum',
  'Countdown',
  'Costco',
  'Coto',
  'Cumberland Farms',
  'CVS Pharmacy',
  'Dia',
  'Dollar General',
  'Dollar Tree',
  'Dunelm',
  'Edeka',
  'El Corte Ingles',
  'FairPrice',
  'Family Dollar',
  'FamilyMart',
  'Food 4 Less',
  'Food Lion',
  'Fred Meyer',
  'Fresh Mart',
  'FreshCo',
  'Giant Eagle',
  'Giant Food',
  'H-E-B',
  'Harris Teeter',
  'Home Bargains',
  'Iceland',
  'IGA',
  'Intermarche',
  'J Sainsbury',
  'Jewel-Osco',
  'Kaufland',
  'Kmart',
  'Kroger',
  'Lawson',
  'Leader Price',
  'Lidl',
  'Loblaw',
  'Lotte Mart',
  'Lulu Hypermarket',
  'Magnit',
  'Makro',
  'Marks & Spencer',
  'Maxima',
  'Meijer',
  'Mercadona',
  'Metro',
  'Migros',
  'Miniso',
  'Monoprix',
  'Morrisons',
  'Netto',
  'No Frills',
  'Ocado',
  'Penny Market',
  'Piggly Wiggly',
  'Publix',
  'Pyaterochka',
  'Ralphs',
  'Real Canadian Superstore',
  'Rewe',
  'Rite Aid',
  'Safeway',
  'Sainsbury',
  'Sainsburys',
  "Sainsbury's",
  "Sam's Club",
  'Save A Lot',
  'Save-On-Foods',
  'Schnucks',
  'Seicomart',
  'ShopRite',
  'Shoprite',
  'Sobeys',
  'Spar',
  'Sprouts Farmers Market',
  'Star Market',
  'Stop & Shop',
  'SuperValu',
  'Target',
  'Tesco',
  'Tesco Express',
  'Trader Joes',
  "Trader Joe's",
  'Vons',
  'Walgreens',
  'Walmart',
  'Walmart Neighborhood Market',
  'Wawa',
  'Wegmans',
  'Winn-Dixie',
  'Woolworths',
  'Waitrose',
  'Whole Foods Market',
].sort((left, right) => left.localeCompare(right))

export const groceryWordLexicon = [
  'apple',
  'apples',
  'ast',
  'avocado',
  'bacon',
  'bagel',
  'bagels',
  'banana',
  'bananas',
  'beans',
  'beef',
  'berries',
  'biscuit',
  'biscuits',
  'bread',
  'broccoli',
  'butter',
  'cake',
  'carrot',
  'carrots',
  'cereal',
  'cheese',
  'chicken',
  'choc',
  'chocolate',
  'coffee',
  'cook',
  'cream',
  'croissant',
  'croissants',
  'cucumber',
  'e',
  'ee',
  'egg',
  'eggs',
  'evaporated',
  'easy',
  'flour',
  'free',
  'grapes',
  'ham',
  'honey',
  'hot',
  'juice',
  'lettuce',
  'lighter',
  'liquid',
  'loaf',
  'milk',
  'mixed',
  'mushroom',
  'mushrooms',
  'oat',
  'onion',
  'onions',
  'orange',
  'oranges',
  'original',
  'pancake',
  'pancakes',
  'pasta',
  'peanut',
  'peanuts',
  'pepper',
  'peppers',
  'pointed',
  'potato',
  'potatoes',
  'protein',
  'range',
  'regal',
  'rice',
  'salad',
  'salmon',
  'salted',
  'sandwich',
  'sardines',
  'sfo',
  'source',
  'spaghetti',
  'spinach',
  'strawberries',
  'strawberry',
  'sugar',
  'tea',
  'toastie',
  'tomato',
  'tomatoes',
  'tuna',
  'veg',
  'vine',
  'washing',
  'water',
  'wht',
  'yoghurt',
  'yogurt',
].sort((left, right) => left.localeCompare(right))
