export const merchantLexicon = [
  'Aldi',
  'Albertsons',
  'Amazon Fresh',
  'Auchan',
  'Asda',
  'Biedronka',
  'Big Bazaar',
  'Big Lots',
  'Billa',
  'BJs Wholesale Club',
  'Boots',
  'Carrefour',
  'Carrefour Express',
  'Casino',
  'City Market',
  'Coles',
  'Co-op',
  'Consum',
  'Countdown',
  'Costco',
  'Coto',
  'Cumberland Farms',
  'CVS Pharmacy',
  'Dia',
  'Dollar General',
  'Dollar Tree',
  'Edeka',
  'El Corte Ingles',
  'FairPrice',
  'Family Dollar',
  'FamilyMart',
  'Food 4 Less',
  'Food Lion',
  'Fred Meyer',
  'Fresh Mart',
  'FreshCo',
  'Giant Eagle',
  'Giant Food',
  'H-E-B',
  'Harris Teeter',
  'Home Bargains',
  'Iceland',
  'IGA',
  'Intermarche',
  'J Sainsbury',
  'Jewel-Osco',
  'Kaufland',
  'Kmart',
  'Kroger',
  'Lawson',
  'Leader Price',
  'Lidl',
  'Loblaw',
  'Lotte Mart',
  'Lulu Hypermarket',
  'Magnit',
  'Makro',
  'Marks & Spencer',
  'Maxima',
  'Meijer',
  'Mercadona',
  'Metro',
  'Migros',
  'Miniso',
  'Monoprix',
  'Morrisons',
  'Netto',
  'No Frills',
  'Ocado',
  'Penny Market',
  'Piggly Wiggly',
  'Publix',
  'Pyaterochka',
  'Ralphs',
  'Real Canadian Superstore',
  'Rewe',
  'Rite Aid',
  'Safeway',
  'Sainsbury',
  'Sainsburys',
  "Sainsbury's",
  "Sam's Club",
  'Save A Lot',
  'Save-On-Foods',
  'Schnucks',
  'Seicomart',
  'ShopRite',
  'Shoprite',
  'Sobeys',
  'Spar',
  'Sprouts Farmers Market',
  'Star Market',
  'Stop & Shop',
  'SuperValu',
  'Target',
  'Tesco',
  'Tesco Express',
  'Trader Joes',
  "Trader Joe's",
  'Vons',
  'Walgreens',
  'Walmart',
  'Walmart Neighborhood Market',
  'Wawa',
  'Wegmans',
  'Winn-Dixie',
  'Woolworths',
  'Waitrose',
  'Whole Foods Market',
].sort((left, right) => left.localeCompare(right))

export const groceryItemLexicon = [
  'Apple',
  'Apples',
  'Avocado',
  'Bacon',
  'Bagel',
  'Banana',
  'Bananas',
  'Beans',
  'Beef',
  'Bread',
  'Broccoli',
  'Butter',
  'Carrot',
  'Carrots',
  'Cereal',
  'Cheese',
  'Chicken',
  'Chocolate',
  'Coffee',
  'Cream',
  'Cucumber',
  'Eggs',
  'Flour',
  'Grapes',
  'Ham',
  'Honey',
  'Juice',
  'Lettuce',
  'Milk',
  'Mushrooms',
  'Oat Milk',
  'Onion',
  'Onions',
  'Orange',
  'Oranges',
  'Pasta',
  'Pepper',
  'Peppers',
  'Potato',
  'Potatoes',
  'Rice',
  'Salad',
  'Salmon',
  'Sandwich',
  'Spinach',
  'Strawberries',
  'Sugar',
  'Tea',
  'Tomato',
  'Tomatoes',
  'Tuna',
  'Water',
  'Yoghurt',
  'Yogurt',
]
